# Generated by Django 3.2.25 on 2026-08-04

import django.core.validators
import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("djangocms_lightbox2", "0006_validate_configuration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lightbox2gallery",
            name="album_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Counter label template. Example: 'Image %1 of %2'. "
                    "Leave blank to use the default value."
                ),
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="lightbox2gallery",
            name="always_show_nav_on_touch_devices",
            field=models.BooleanField(
                default=False,
                help_text="Always show navigation on touch devices.",
            ),
        ),
        migrations.AlterField(
            model_name="lightbox2gallery",
            name="carousel_aspect_ratio",
            field=models.CharField(
                choices=[
                    ("16-9", "16:9 (widescreen)"),
                    ("4-3", "4:3 (standard)"),
                    ("1-1", "1:1 (square)"),
                    ("3-2", "3:2 (classic photo)"),
                    ("21-9", "21:9 (cinematic)"),
                ],
                default="4-3",
                help_text="Aspect ratio for the main carousel area.",
                max_length=10,
                verbose_name="Aspect ratio",
            ),
        ),
        migrations.AlterField(
            model_name="lightbox2gallery",
            name="carousel_background_color",
            field=models.CharField(
                default="#F8F8F8",
                help_text="Background color applied to the main carousel area.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color in the format #RRGGBB.",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
                verbose_name="Background color",
            ),
        ),
        migrations.AlterField(
            model_name="lightbox2gallery",
            name="carousel_object_fit",
            field=models.CharField(
                choices=[
                    ("cover", "cover"),
                    ("contain", "contain"),
                    ("fill", "fill"),
                    ("none", "none"),
                    ("scale-down", "scale-down"),
                ],
                default="cover",
                help_text="CSS object-fit value used for images in the carousel.",
                max_length=10,
                verbose_name="Object fit",
            ),
        ),
        migrations.AlterField(
            model_name="lightbox2gallery",
            name="disable_scrolling",
            field=models.BooleanField(
                default=False,
                help_text="Disable background scrolling when open.",
            ),
        ),
        migrations.AlterField(
            model_name="lightbox2gallery",
            name="fit_images_in_viewport",
            field=models.BooleanField(
                default=True,
                help_text="Fit images to the viewport.",
            ),
        ),
        migrations.AlterField(
            model_name="lightbox2gallery",
            name="limit_items",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Limit of images to display (0-1000; blank for all).",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="lightbox2gallery",
            name="show_image_number_label",
            field=models.BooleanField(
                default=True,
                help_text="Show image number label.",
            ),
        ),
        migrations.AlterField(
            model_name="lightbox2gallery",
            name="wrap_around",
            field=models.BooleanField(
                default=False,
                help_text="Allow wrap-around navigation.",
            ),
        ),
        migrations.AlterField(
            model_name="lightbox2image",
            name="image",
            field=filer.fields.image.FilerImageField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.FILER_IMAGE_MODEL,
            ),
        ),
    ]
