name: Tests

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8

      - name: Run black
        run: black --check .

      - name: Run isort
        run: isort --check-only .

      - name: Run flake8
        run: flake8 .

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: django32-cms311
            python: '3.10'
            django: '>=3.2,<3.3'
            cms: '>=3.11,<3.12'
          - name: django42-cms41
            python: '3.10'
            django: '>=4.2,<4.3'
            cms: '>=4.1,<4.2'
          - name: django42-cms50
            python: '3.10'
            django: '>=4.2,<4.3'
            cms: '>=5.0,<5.1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            "Django${{ matrix.django }}" \
            "django-cms${{ matrix.cms }}" \
            django-filer \
            easy-thumbnails \
            django-sekizai \
            pytest pytest-django

      - name: Run tests
        run: |
          pytest -q
