name: I18N Check

on:
  push:
  pull_request:

jobs:
  compile-and-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install gettext (msgfmt)
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext

      - name: Compile translations (.po -> .mo)
        run: |
          set -euo pipefail
          shopt -s nullglob
          for po in djangocms_lightbox2/locale/*/LC_MESSAGES/*.po; do
            mo="${po%.po}.mo"
            msgfmt -o "$mo" "$po"
          done

      - name: Verify no changes after compile
        run: |
          if ! git diff --quiet; then
            echo "Translation .mo files are out of date with .po sources." >&2
            echo "Please compile messages locally before committing:" >&2
            echo "  find djangocms_lightbox2/locale -name '*.po' -exec bash -c 'msgfmt -o \"${1%.po}.mo\" \"$1\"' _ {} \;" >&2
            git --no-pager diff --name-only
            exit 1
          fi

  build-and-verify:
    runs-on: ubuntu-latest
    needs: compile-and-verify
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build sdist and wheel
        run: |
          python -m build

      - name: Twine check metadata
        run: |
          python -m twine check dist/*

      - name: Verify locale files included in sdist
        run: |
          set -euo pipefail
          SDIST=$(ls dist/*.tar.gz)
          echo "Checking $SDIST"
          tar -tzf "$SDIST" | grep -E 'djangocms_lightbox2/locale/.+/LC_MESSAGES/django\.mo' >/dev/null || {
            echo "Missing compiled .mo files in sdist" >&2; exit 1; }

      - name: Verify locale files included in wheel
        run: |
          set -euo pipefail
          WHEEL=$(ls dist/*.whl)
          echo "Checking $WHEEL"
          unzip -l "$WHEEL" | grep -E 'djangocms_lightbox2/locale/.+/LC_MESSAGES/django\.mo' >/dev/null || {
            echo "Missing compiled .mo files in wheel" >&2; exit 1; }
